### ISSUE TITLE
Raids aren't returning any resources

### ISSUE THREAD

**Issue by ioneethling** [BlauhausTechnology/MoonbaseIssues#1]
My last two raids(will try attach picture) have been getting resources, but when units return nothing is added

**Comment by ioneethling** [comment]
I mean none of the resources are added to my silo

**Comment by freever** [comment]
![image](https://user-images.githubusercontent.com/2269624/53282284-5f6d2800-373e-11e9-833f-93f8b707572c.png)

**Comment by freever** [comment]
The 4050 and 4800 attack there didn't return any resources to base
The others one may have also behaved the same, but wasn't paying much attention then

**Comment by Thaldoras** [comment]
![attackresourceglitch](https://user-images.githubusercontent.com/13771433/53283149-8893b580-374a-11e9-9682-f782ed3e4164.jpeg)

This is an attack I made.

**Comment by freever** [comment]
@Thaldoras Serves you right for attacking Zeus

**Comment by freever** [comment]
Confirmed bug, fix on the way

**Comment by freever** [comment]
Fixed and deployed, thanks for the report!
