### ISSUE TITLE
Units not returning after raid

### ISSUE THREAD

**Issue by ioneethling** [BlauhausTechnology/MoonbaseIssues#10]
This should be looked at with issue 9, but might not be related. So the full scenario is I was launching an attack and it showed I had launched an attack, but it still showed I had the same amount of units left available for an attack, as described in issue #9, then I tried launching those and it failed as I also described in issue #9. So when my units returned from the successful raid for a while they were not visible in base, but after I queued a new gs they reappeared. I should also mention that even though the units were invisible and also not available for an attack the resources from the raid did appear in my solo.

**Comment by ioneethling** [comment]
Correction, they appear exactly after I launch an attack, not when I queued a new unit.

**Comment by ioneethling** [comment]
This has now happened twice on different bases

**Comment by ioneethling** [comment]
I can confirm that the second time I did not experience the problems from #9, so if they're related the effects of trying to launch units that just seem to be there because of UI updating problems may be permanent, but doubt it.

**Comment by freever** [comment]
Can you please pop in a screenshot or some specific details about the time of the attack so I can trace it down in the logs?

**Comment by ioneethling** [comment]
So what I've noticed is this only affects my second base. The units returning after sending out an attack does not seem to work anymore , and also my units disappeared while being transferred to that base now as well

**Comment by ioneethling** [comment]
What's with the timestamp? You talking to yourself?

**Comment by freever** [comment]
> What's with the timestamp? You talking to yourself?

Just putting in a timestamp so I can trace the logs in future.

I'm seeing a "Failed to restore MovementEntity" error in the logs when you load the game - is this error visible to you?

**Comment by ioneethling** [comment]
No, haven't seen that

**Comment by ioneethling** [comment]
Perhaps give me the 170 gs again so I can attempt to reporduce?

**Comment by freever** [comment]
I've tested with an attack from your second base and it worked fine, I also managed to transfer one gun from 1 to 2 and it also worked, so I'm thinking there must be corrupted data on your device. Could you try hitting the Clear Cache button on the menu please, and let me know if it helps?

**Comment by ioneethling** [comment]
The sending out an attack thing was actually working consistently until my third or fourth try

**Comment by ioneethling** [comment]
Will attempt that now, but did clear all data earlier

**Comment by ioneethling** [comment]
But that was because my game got stuck on Updating

**Comment by ioneethling** [comment]
Tested again now. Attacks work fine, but earlier I had to go through a cycle of raiding, and sending out a scout so I had access to the units that became 'invisible' at least 3 times , but as mentioned that also stopped working

**Comment by freever** [comment]
Thanks, found the bug.

**Comment by MoonbaseRey** [comment]
My version of this bug: Transferred 5 raiders from #1 to #2. Launched an attack. Same 5 raiders were visible the whole time 'at base'.  As soon as units landed at base, the 5 raiders that were displayed changed to '0'.  This was an issue on Alpha as well with transferred units if I remember correctly
