### ISSUE TITLE
Units disappearing after transfer

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#11]
Transferred one raider from #1 to #2 to check if the issue was resolved. Saw movement, movement was completed, but unit not displaying at #2

**Comment by freever** [comment]
related but different to #10

**Comment by freever** [comment]
Actually I think this is due to bum data caused by #10, not a new issue. I've cleaned out all the bad data I could find, let's see if it works....

**Comment by freever** [comment]
confirmed duplicate
