### ISSUE TITLE
Game broke after taking a 1-2 hour break

### ISSUE THREAD

**Issue by ioneethling** [BlauhausTechnology/MoonbaseIssues#20]
After taking a short break I came back to negative resources and also lost about 4k bugs

**Comment by ioneethling** [comment]
![image](https://user-images.githubusercontent.com/16287268/53566945-6513a500-3b66-11e9-9f24-71a0f125aa49.png)

**Comment by ioneethling** [comment]
Note the negative resources there

**Comment by ioneethling** [comment]
and whatever is happening here 
![image](https://user-images.githubusercontent.com/16287268/53567028-a015d880-3b66-11e9-8bab-555f97636c41.png)

**Comment by ioneethling** [comment]
I will experiment with what I can do with the negative res in a second

**Comment by freever** [comment]
this was a timing glitch to do with the sequencing of server shut downs... should be fixed for future shutdowns
