### ISSUE TITLE
Text Sometimes Doesn't Display Correctly 

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#21]
In the image below. the name circled in green should say vollmond.

![whatsapp image 2019-02-28 at 11 34 15](https://user-images.githubusercontent.com/13771433/53568914-d013aa80-3b6b-11e9-94d8-2e8a8710cbd5.jpeg)

**Comment by freever** [comment]
when you say "sometimes".... can you identify anything that might cause or correlate with this?

**Comment by Thaldoras** [comment]
It seems to be random. I will try look for a cause.

**Comment by freever** [comment]
duplicate of #23 

Will only be able to debug this when we have a server with more players as that is when it seems to happen
