### ISSUE TITLE
Ranks displayed incorrectly

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#23]
What the title says

**Comment by freever** [comment]
ios:
https://files.slack.com/files-pri/TDL5E4UDQ-FGNQDFJCE/file.jpg

android:
https://files.slack.com/files-pri/TDL5E4UDQ-FGMM8K38D/screenshot_20190302-110413.png

**Comment by MrGr33n47** [comment]
Same here..

**Comment by freever** [comment]
Can anyone remember this happening in the version we played last year? I haven't really changed much in this list...
