### ISSUE TITLE
Map artifacts have returned

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#27]
During multiple attacks this morning red and green lines were flashing all over the screen while moving around the map. Now it is just the plots like previously reported. It gets progressively worse the more radar upgrades yu do

**Comment by freever** [comment]
does it get better after you restart the app

**Comment by MoonbaseRey** [comment]
Will launch some attach and check

**Comment by MoonbaseRey** [comment]
No it remains the same

**Comment by freever** [comment]
Can you upload a video perhaps?

**Comment by freever** [comment]
https://www.dropbox.com/s/oz1avjbp0mgd0z4/C734496F-79CF-4DB8-ACF3-C9E74874043C.MP4?dl=0

**Comment by freever** [comment]
This was due to some changes I made to allow the device to reconnect itself if the connection drops... long story short it should be fixed in 0.14.6
