### ISSUE TITLE
Helium Consumption Upgrades on 30x

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#31]
Helium consumption upgrades display the incorrect value and that incorrect value is used to calculate the helium production of bases. I only tested this with grunts.

Value Displayed: | Correct Value:(10x the decrease on a 1x server)
------------ | -------------
Level 0: 10/hr | Level 0: 10/hr
Level 1: 9/hr | Level 1: 9.8/hr
Level 2: 9/hr | Level 2: 9.6/hr
Level 3: 9/hr | Level 3: 9.4/hr
Level 4: 9/hr | Level 4: 9.2/hr
Level 5: 9/hr | Level 5: 8.8/hr
Level 6: 8/hr | Level 6: 8.6/hr

I think my correct values are actually wrong. I am trying to work from memory. But you should get the idea I hope.

**Comment by freever** [comment]
@Thaldoras I've deployed a change that should fix this - you might need to restart the app to see it but both display and calculation should be correct now. Is it?

**Comment by Thaldoras** [comment]
Yes it seems to be correct.
