### ISSUE TITLE
Troop Construction Being Undone

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#32]
If you have troops in que, for example gunships. Then If you send Gunships out on an attack When they return: the gunships that were constructed while they were out are removed and added back onto your que. 

This glitch effectively results in you losing no resources you have spent. But it does prevent your army from growing or rather, it slows your growth down.

**Comment by freever** [comment]
So let's say I have 20 gunships with 10 in the queue. I launch an attack, which returns with all 20 gunships. Between the time I launched the attack and its returning, 5 gunships were constructed, so I should have 25 gunships with 5 in the queue. Instead I have 20 gunships with 10 in the queue. 

Am I understanding correctly?

**Comment by freever** [comment]
replicated
