### ISSUE TITLE
No Incoming Attack alert

### ISSUE THREAD

**Issue by MoonbaseRey** [BlauhausTechnology/MoonbaseIssues#6]
No alerts of incoming attacks on base #2. No 'line' or tab lighting up.  Was tested 3 times between myself and Andrew. Reports do show afterward.

**Comment by freever** [comment]
Did you see the incoming attacks triangle light up on your base screen? Was there anything on the incoming attacks list screen? In other words was this attack completely invisible or just not visible in certain parts of the app?

**Comment by Thaldoras** [comment]
Attack was completely invisible.

**Comment by freever** [comment]
Closing this - we can reopen if it happens again
