### ISSUE TITLE
Announcement System which Uses the Chat Feature

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#7]
The game will need an in game announcement system when it launches. This will be needed as new players wont necessarily use social media to view announcements. Such a system can use the chat feature. An admin account can be used to send out broadcast announcements.

I am unaware if such a system has been implemented already.

**Comment by freever** [comment]
Yes I was thinking along the same lines wrt using an admin chat (readonly of course) to broadcast messages. In the mean time I can send push notifications to all devices, but it's a pretty blunt instrument
