### ISSUE TITLE
Viewing Defense Reports

### ISSUE THREAD

**Issue by Thaldoras** [BlauhausTechnology/MoonbaseIssues#8]
Currently. The only way a player can view defense reports is if they can see the base which attacked them. Else they have to get alliance members to screenshot the report and send it to them.

I believe the game needs a defense report menu where a player can view all the defense reports of their bases. A button to access this menu can be added to the menu which opens when you press the button in top left hand corner. (Only until the UI is reworked, then a more elegant solution can be implemented)

**Comment by freever** [comment]
If you tap on the incoming attacks button on your base (the down arrow on the right) you see all attacks that arrived on your base even if they came from outside your range.... not so?

**Comment by MoonbaseRey** [comment]
Yes that is correct @freever

**Comment by Thaldoras** [comment]
@freever That is correct. I forgot about that and have been trying all kinds of work arounds. (－‸ლ)

**Comment by freever** [comment]
Eventually I want to give each of those arrows an "unread" indicator that shows you if new movements have arrived.... that requires me to track which movements in which state you've viewed on which devices though, so it's on the back-burner for now.
